<?php

namespace Badenjki\Seller\Models;

use Webkul\Customer\Models\Customer;

class Seller extends Customer
{

    protected $table = 'customers';

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(function ($query){
            $query->whereNotNull('store_id');
        });

    }

}
