<?php

namespace Badenjki\Seller\Models;

use Webkul\Customer\Models\Customer;
use Badenjki\Seller\Contracts\Seller as SellerContract;
class Seller extends Customer implements SellerContract
{

    protected $table = 'customers';

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(function ($query){
            $query->whereNotNull('store_id');
        });

    }

}
